language: vi

pipeline:
- name: SpacyNLP
#      model: vi-core-news-lg
- name: SpacyTokenizer
#      - name: SpacyFeaturizer
- name: RegexFeaturizer
#      - name: "VietnameseTokenizer"
- name: "sentiment_analysis.SentimentAnalyzer"
- name: "RegexFeaturizer"
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
  
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy